server:
  port: 10000

spring: 
  application:
    name: scholat-user-client
  
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:7001/eureka/
      
feign: 
  hystrix: 
    enabled: true