spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scholat
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
      #修改默认生成策略，数据库驼峰式命名
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    控制台显示SQL
    show-sql: true
    database: mysql
   #    禁用缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML5

server:
  port: 9001

