server:
  port: 9010

spring:
  application:
    name: scholat-provider-detail
#  main:
#    allow-bean-definition-overriding: true  #允许同名覆盖

#配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scholat?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
#mybatis配置文件位置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  type-aliases-package: org.scholat.provider.detail.entity


#设置日志级别，输出sql执行过程
logging:
  level:
    org.scholat.proviser.course.mapper: trace #设置mapper包日志级别为trace

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: detail-server   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址


feign:
  hystrix:
    enabled: true


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql