#端口
server:
  port: 9001

spring:
  application:
    name: scholat-user #微服务的应用名称    
#连接数据库配置    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scholat?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#Jpa一些配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#配置redis    
  redis:
    host: 39.97.184.214
    port: 6379
    password: root   
    
#客户端注册进eureka服务列表内    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: user-server   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
 
#开启hystrix
feign:
  hystrix:
    enabled: true
   


  
    
