#端口
server:
  port: 8001

#网关名
spring:
  application:
    name: scholat-gateway
#配置redis    
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: root 
    
#注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#第一种写法
#zuul:
#  prefix: /scholat
#  routes:
#    user:
#      path: /user/**
#      serviceId: scholat-user
#      strip-prefix: false


#路由配置，第二种写法
zuul:
  sensitiveHeaders:  #不过滤cookie
  prefix: /scholat
  routes:
    scholat-userLogin: /user/**
    scholat-course: /course/**
    scholat-question: /question/**
    scholat-notice: /notice/**
    scholat-task: /task/**
    #微服务应用实例名: /xxxx/***
    
